sonar.projectKey=Jair-Noto_AsaiPro
sonar.organization=jair-noto

sonar.sources=.
sonar.exclusions=vendor/**,tests/**,.github/**
sonar.test.inclusions=tests/**/*.php


sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
